#!/bin/sh

# pCP script to update Raspberry Pi4/5 boot EEPROM.

VERSION="28.30-1-pCP"

. /etc/init.d/tc-functions
. /var/www/cgi-bin/pcp-functions

checknotroot

update_ext() {
	WGET="busybox wget"
	DIFF="busybox diff"
	MD5="busybox md5sum"
	EXTENSION_DIR=/etc/sysconfig/tcedir/optional
	UPGRADE_DIR=${EXTENSION_DIR}/upgrade

	rm -f /tmp/rpi-eeprom.tcz*

	echo "[ INFO ] Checking for package update: rpi-eeprom.tcz"
	echo "[ INFO ] You are running release $VERSION"
	LATEST=$($WGET -q https://api.github.com/repos/piCorePlayer/rpi-eeprom/releases/latest -O - | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
	echo "[ INFO ] The latest release is $LATEST"

	$WGET -q https://github.com/piCorePlayer/rpi-eeprom/releases/latest/download/rpi-eeprom.tcz.md5.txt -P /tmp
	$DIFF -q /tmp/rpi-eeprom.tcz.md5.txt /etc/sysconfig/tcedir/optional/rpi-eeprom.tcz.md5.txt >/dev/null 2>&1
	if [ $? -eq 0 ]; then
	   echo "[ INFO ] Extension version Matches"
   	exit 2
	else
	   echo "[ INFO ] Update Required."
	   $WGET -q https://github.com/piCorePlayer/rpi-eeprom/releases/latest/download/rpi-eeprom.tcz -P /tmp
	fi

	[ -d $UPGRADE_DIR ] || mkdir -p $UPGRADE_DIR
	cd /tmp
	echo "[ INFO ] Validating MD5's of new extensions"
	$MD5 -cs rpi-eeprom.tcz.md5.txt
	if [ $? -eq 0 ]; then
	   mv -f /tmp/rpi-eeprom.tcz* ${UPGRADE_DIR}
	else
	   echo "[ERROR] rpi-eeprom.tcz failed md5 check."
	   exit 1
	fi

	echo "[ INFO ] A reboot is needed to load new rpi-eeprom extension."
	exit
}

usage() {
	echo "Usage:"
	echo "$0 --update:   Update rpi-eeprom.tcz extension"
	echo ""
	echo "The default firmware upgrade is from the critical firmware branch"
	echo "  to override, set the FIRMWARE_RELEASE_STATUS environmen variable"
	echo "  export FIRMWARE_RELEASE_STATUS=<default|latest>"
   echo ""
	echo "----------------------------------------------"
	echo ""
	echo "rpi-eeprom-update options"
	rpi-eeprom-update -h
	exit
}


OPTS=""
for A in $@; do
	case $A in
		--update) update_ext;;
		--help) usage;;
		*)OPTS="$OPTS $A";;
	esac
done

pcp_mount_bootpart text >/dev/null 2>&1

if [ ! -f ${PACKAGEDIR}/raspi-utils.tcz -a ! -f ${PACKAGEDIR}/rpi-vc.tcz ]; then
	echo "raspi-utils extension is required for this tool"
	exit 1
elif [ ! -f /usr/local/bin/vcgencmd ]; then
	if [ -f ${PACKAGEDIR}/raspi-utils.tcz ]; then
		tce-load -i raspi-utils.tcz
	elif [ -f ${PACKAGEDIR}/rpi-vc.tcz ]; then
		tce-load -i rpi-vc.tcz
	fi
fi

if [ ! -f ${PACKAGEDIR}/pciutils.tcz ]; then
	echo "pciutils extension is required for this tool"
	exit 1
elif [ ! -f /usr/local/bin/lspci ]; then
	tce-load -i pciutils.tcz
fi

PY_MIN_VER=8
highest=""

for f in "${PACKAGEDIR}"/python3.*.tcz; do
	[ -e "$f" ] || continue  # no matches

	base=$(basename "$f")          # python3.14.tcz
	minor=${base#python3.}         # 14.tcz
	minor=${minor%.tcz}            # 14

	case "$minor" in
		''|*[!0-9]*) continue ;;     # skip non-numeric
	esac

	if [ "$minor" -ge "$PY_MIN_VER" ]; then
		if [ -z "$highest" ] || [ "$minor" -gt "$highest" ]; then
			highest="$minor"
		fi
	fi
done

if [ -n "$highest" ]; then
	PYTHON3PKG="python3.${highest}.tcz"
else
	PYTHON3PKG=""
fi

if [ ! -f ${PACKAGEDIR}/$PYTHON3PKG ]; then
	echo "python 3 verison $PY_MIN_VER or higher is required for this tool"
	exit 1
elif [ ! -f /usr/local/bin/python3 ]; then
	tce-load -i $PYTHON3PKG
fi

[ ! -x /usr/local/bin/python ] && sudo ln -s /usr/local/bin/python3 /usr/local/bin/python

echo "pCP rpi-eeprom package version: $VERSION"
sudo -E rpi-eeprom-update $OPTS
