blank_issues_enabled: false

contact_links:
  - name: "⛔ Question"
    url: https://www.raspberrypi.org/forums
    about: "Please do not use GitHub for asking questions. If you simply have a question, then the Raspberry Pi forums are the best place to ask it. Thanks in advance for helping us keep the issue tracker clean!"
  - name: "⛔ Problems with Raspberry Pi Imager / network-install"
    url: https://github.com/raspberrypi/rpi-imager
    about: "If the problem with network install occurs after the Raspberry Pi Imager UI has started then please report it at https://github.com/raspberrypi/rpi-imager/issues. Otherwise, raise the bug report here."
