name: Version Check

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 3 * * *'

jobs:
  Check:
    name: Check if update needed
    if: ${{ github.repository_owner == 'piCorePlayer' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const response = await fetch('https://raw.githubusercontent.com/raspberrypi/rpi-eeprom/pios/bookworm/debian/changelog');
            if (!response.ok){
              console.error('Fetching rpi changelog failed' + response.status);
              return false;
            }
            const changelog = await response.text();
            const firstLine = changelog.split('\n')[0];
            const match = firstLine.match(/\(([^)]+)\)/);
            const changelogVersion = match ? match[1] : null;
            console.log('First line:', firstLine);
            console.log('Parsed version:', changelogVersion);


            const release = await github.rest.repos.getLatestRelease({ owner: 'piCorePlayer', repo: 'rpi-eeprom' });
            const releaseTag = release.data.tag_name;

            const githubTag = releaseTag.startsWith('v') ? releaseTag.slice(1) : releaseTag;
            const githubVersion = githubTag.split('-').slice(0, 2).join('-');
            
            console.log('Changelog version:', changelogVersion);  
            console.log('GitHub release version:', githubVersion);

            if (changelogVersion === githubVersion) {
                console.log('Versions match!');
            } else {
               console.log('Versions differ, triggering update workflow...');
               await github.rest.actions.createWorkflowDispatch({
                 owner: 'piCorePlayer',
                 repo: 'rpi-eeprom',
                 workflow_id: 'merge_upstream.yml',
                 ref: 'pCP',
                 inputs: {
                   changelogVersion
                 }
               });
            }
