name: Release Extension

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Extension
#    runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: rpi_eeprom_git

      - name: Copy Code
        run: |
             mkdir -p sqfs-root/lib/firmware/raspberrypi/bootloader-2711
             mkdir -p sqfs-root/lib/firmware/raspberrypi/bootloader-2712
             mkdir -p sqfs-root/usr/local/bin
             mkdir -p sqfs-root/etc/default
             mkdir -p sqfs-root/usr/local/share/rpi-eeprom
             cp rpi_eeprom_git/rpi-eeprom-config sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/rpi-eeprom-digest sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/rpi-eeprom-update sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/pcp-rpi-eeprom-* sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/rpi-eeprom-update-default-pcp sqfs-root/etc/default/rpi-eeprom-update
             chmod 755 sqfs-root/usr/local/bin/*

             cp rpi_eeprom_git/LICENSE sqfs-root/usr/local/share/rpi-eeprom

             cp -r rpi_eeprom_git/firmware-2711/default sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/latest sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/critical sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/stable sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/beta sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp rpi_eeprom_git/firmware-2711/release-notes.md sqfs-root/lib/firmware/raspberrypi/bootloader-2711/

             cp -r rpi_eeprom_git/firmware-2712/default sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/latest sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/critical sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/stable sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/beta sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp rpi_eeprom_git/firmware-2712/release-notes.md sqfs-root/lib/firmware/raspberrypi/bootloader-2712/

      - name: Create Extension
        id: make_tcz
        run: |
            mksquashfs ./sqfs-root rpi-eeprom.tcz -b 16384
            md5sum rpi-eeprom.tcz > rpi-eeprom.tcz.md5.txt

      - name: List Extension
        run: unsquashfs -ll rpi-eeprom.tcz | tee rpi-eeprom.tcz.list

      - name: Create a Release in a GitHub Action
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.RPI_EEPROM_RELEASE }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            rpi-eeprom.tcz
            rpi-eeprom.tcz.md5.txt
            rpi-eeprom.tcz.list
