name: Release Extension

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Create Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: rpi_eeprom_git

      - name: Copy Code
        run: |
             mkdir -p sqfs-root/lib/firmware/raspberrypi/bootloader-2711
             mkdir -p sqfs-root/lib/firmware/raspberrypi/bootloader-2712
             mkdir -p sqfs-root/usr/local/bin
             mkdir -p sqfs-root/etc/default
             cp rpi_eeprom_git/rpi-eeprom-config sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/rpi-eeprom-digest sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/rpi-eeprom-update sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/pcp-rpi-eeprom-update sqfs-root/usr/local/bin/
             cp rpi_eeprom_git/rpi-eeprom-update-default-pcp sqfs-root/etc/default/rpi-eeprom-update

             cp -r rpi_eeprom_git/firmware-2711/default sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/latest sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/critical sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/stable sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp -r rpi_eeprom_git/firmware-2711/beta sqfs-root/lib/firmware/raspberrypi/bootloader-2711/
             cp rpi_eeprom_git/firmware-2711/release-notes.md sqfs-root/lib/firmware/raspberrypi/bootloader-2711/

             cp -r rpi_eeprom_git/firmware-2712/default sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/latest sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/critical sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/stable sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp -r rpi_eeprom_git/firmware-2712/beta sqfs-root/lib/firmware/raspberrypi/bootloader-2712/
             cp rpi_eeprom_git/firmware-2712/release-notes.md sqfs-root/lib/firmware/raspberrypi/bootloader-2712/

      - name: Create a Release in a GitHub Action
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.RPI_EEPROM_RELEASE }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Create Extension
        id: make_tcz
        run: |
            mksquashfs ./sqfs-root rpi-eeprom.tcz
            md5sum rpi-eeprom.tcz > rpi-eeprom.tcz.md5.txt

      - name: List Extension
        run: unsquashfs -ll rpi-eeprom.tcz

      - name: Upload Release Asset
        id: upload-release-asset-tcz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RPI_EEPROM_RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rpi-eeprom.tcz
          asset_name: rpi-eeprom.tcz
          asset_content_type: application/data

      - name: Upload Release Asset
        id: upload-release-asset-md5
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RPI_EEPROM_RELEASE }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rpi-eeprom.tcz.md5.txt
          asset_name: rpi-eeprom.tcz.md5.txt
          asset_content_type: application/data
